### PR TITLE
Update Makefile to use newer kubebuilder when generating manifests

### PR DESCRIPTION
**Pull request by awels**
Updated Makefile arguments to match newer kubebuilder requirements.

### CODE REVIEW

**Review by pranavgaikwad — COMMENTED** [review]
This change looks good to me. I am not sure how that affects operator / release things. @jmontleon Let me know what you think about this

**Review by jmontleon — APPROVED** [review]
ACK

**Comment by jmontleon** [comment]
They'll need to be copied to 
https://github.com/migtools/mig-operator/tree/master/deploy/olm-catalog/bundle/manifests

It looks like the leading empty lines got deleted? This is good; they break the operator if they remain...

**Comment by awels** [comment]
Hmm it never notified me about these comments, I will take care of copying the stuff to the olm bundle.

**Comment by awels** [comment]
> They'll need to be copied to https://github.com/migtools/mig-operator/tree/master/deploy/olm-catalog/bundle/manifests
> 
> It looks like the leading empty lines got deleted? This is good; they break the operator if they remain...

Matching PR to update OLM bundle https://github.com/migtools/mig-operator/pull/903

**Review by rayfordj — APPROVED** [review]
/lgtm

**Pull request merged**
